version: '3' 

services:

  mysqldb:
    image: mysql-image
    build: ./chat/mysql
    volumes:
      - ./chat/mysql/conf:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: abc
      MYSQL_USER: abc
      MYSQL_PASSWORD: abc
    networks:
      - CHATNET

  chat:
    image: chat-image
    build: ./chat
    ports:
      - "8080:8080"   
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/mydatabase
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_USERNAME: abc
      SPRING_DATASOURCE_PASSWORD: abc
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - CHATNET 

networks:
  CHATNET:
