version: '3'

services:
  chat:
    image: chat-image
    build: ./chat
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: chat_db
      DATABASE_USER: root
      DATABASE_PASSWORD: cnse
      DATABASE_NAME: chat_db
    depends_on:
      - chat_db
    networks:
      - CHATNET

  adminer:
    image: adminer
    restart: always
    ports: 
      - "8082:8080"
    networks:
      - CHATNET

  chat_db:
    image: chat_db-image
    build: ./chat_db
    environment:
      MYSQL_ROOT_PASSWORD: cnse
      MYSQL_DATABASE: chat_db
    ports:
      - "3308:3306"
    networks:
      - CHATNET

  user_db:
    image: user_db-image
    build: ./user_db
    environment:
      MYSQL_ROOT_PASSWORD: cnse
      MYSQL_DATABASE: user_db
    networks:
      - CHATNET      

networks:
  CHATNET:
